CREATE TABLE [dbo].[f_Requests]
(
[LOG_PK] [int] NOT NULL,
[LOG_REQUESTOR] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_REQ_DATE] [datetime] NULL,
[LOG_LOC_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_BLDG] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_AREA_NO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_REQUEST] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOG_EMAILED] [smallint] NULL,
[LOG_EMAIL_ADDR] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_REJECT_DATE] [datetime] NULL,
[LOG_REJECTOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_REJ_REASON] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_ACCEPTOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_ACCEPT_DATE] [datetime] NULL,
[LOG_LT_FK] [int] NULL,
[LOG_WO_FK] [int] NULL,
[LOG_COMMENTS] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_NUMBER] [float] NOT NULL,
[LOG_MOD_DATE] [datetime] NULL,
[LOG_MOD_USER] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_FAC_ID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_RC_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CLIENT] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_STATUS] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_EST_COST] [float] NULL,
[LOG_REQ_PHONE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_TAG_DESC] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_TAG_NO] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_RQ_FK] [int] NULL,
[LOG_REQ_TIME] [datetime] NULL,
[LOG_CREATE_DATE] [datetime] NULL,
[LOG_CREATOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_NUM_2DP1] [float] NULL,
[LOG_NUM_2DP2] [float] NULL,
[LOG_NUM_2DP3] [float] NULL,
[LOG_NUM_2DP4] [float] NULL,
[LOG_NUM_4DP1] [float] NULL,
[LOG_NUM_4DP2] [float] NULL,
[LOG_NUM_4DP3] [float] NULL,
[LOG_NUM_4DP4] [float] NULL,
[LOG_NUM_4DP5] [float] NULL,
[LOG_NUM_4DP6] [float] NULL,
[LOG_NUM_INT_1] [float] NULL,
[LOG_NUM_INT_2] [float] NULL,
[LOG_BOOLEAN_1] [smallint] NULL,
[LOG_BOOLEAN_2] [smallint] NULL,
[LOG_BOOLEAN_3] [smallint] NULL,
[LOG_BOOLEAN_4] [smallint] NULL,
[LOG_BOOLEAN_5] [smallint] NULL,
[LOG_BOOLEAN_6] [smallint] NULL,
[LOG_CHAR_60_1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_60_2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_30_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_30_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_30_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_30_4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_255_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_255_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_255_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_255_4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_CHAR_255_5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOG_UD_DATE1] [datetime] NULL,
[LOG_UD_DATE2] [datetime] NULL,
[LOG_UD_DATE3] [datetime] NULL,
[LOG_UD_DATE4] [datetime] NULL,
[LOG_UD_DATE5] [datetime] NULL,
[LOG_UD_DATE6] [datetime] NULL,
[LOG_FM_FK] [int] NULL,
[LOG_NS_FK] [int] NULL,
[LOG_FV_FK] [int] NULL,
[LOG_P_FK] [int] NULL,
[LOG_CR_FK] [int] NULL,
[LOG_GRP_FK] [int] NULL,
[LOG_CE_FK] [int] NULL,
[LOG_FU_FK] [int] NULL,
[LOG_CN_FK] [int] NULL,
[LOG_FB_FK] [int] NULL,
[LOG_AUTHORIZED] [smallint] NULL,
[LOG_AUTH_DATE] [datetime] NULL,
[LOG_LEGACY_AUTH] [smallint] NULL,
[LOG_AUTH_REQD] [smallint] NULL,
[LOG_PR_FK] [int] NULL
) ON [PRIMARY]
GO
