CREATE TABLE [dbo].[f_WorkOrder]
(
[WO_EQUIP_TYPE] [float] NULL,
[WO_PRIORITY] [float] NULL,
[WO_REQUEST_DATE] [datetime] NOT NULL,
[WO_ASSIGN_DATE] [datetime] NULL,
[WO_CLOSE_DATE] [datetime] NULL,
[WO_LABOR_COST] [float] NULL,
[WO_EQ_DWNTIME] [float] NULL,
[WO_ACT_REQ] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_TYPE_CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WO_POST_DATE] [datetime] NULL,
[WO_CHARGE] [smallint] NULL,
[WO_NUMBER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WO_PK] [int] NOT NULL,
[WO_EQUIP_TAG] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_REQUESTOR] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_STATUS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_TOTAL_COST] [float] NULL,
[WO_PARTS_COST] [float] NULL,
[WO_EQUIP_DESCR] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_REQUEST_TIME] [datetime] NULL,
[WO_EST_TIME] [float] NULL,
[WO_ACCT_NO] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_HOURS_TOTAL] [float] NULL,
[WO_ALT_PHONE] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_HOURS_POST] [float] NULL,
[WO_SUPERVISOR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_LABOR_POST] [float] NULL,
[WO_TOTAL_POST] [float] NULL,
[WO_PARTS_POST] [float] NULL,
[WO_OTHER_POST] [float] NULL,
[WO_EST_COST] [float] NULL,
[WO_CON_NO] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CONT_CODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CONT_NAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_PREF_CONT] [smallint] NULL,
[WO_EST_ADJ] [float] NULL,
[WO_CLOSE_TIME] [datetime] NULL,
[WO_LAST_PRINT] [datetime] NULL,
[WO_MOD_DATE] [datetime] NULL,
[WO_MOD_USER] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_ARCH_DATE] [datetime] NULL,
[WO_RC_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WO_OP_ERR] [smallint] NULL,
[WO_OP_RISK] [smallint] NULL,
[WO_CR_SGN1] [datetime] NULL,
[WO_CR_SGN2] [datetime] NULL,
[WO_PRJ_CODE] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_PAT_RISK] [smallint] NULL,
[WO_DEPT_ACT] [smallint] NULL,
[WO_WARRANT_JOB] [smallint] NULL,
[WO_SERVICE_JOB] [smallint] NULL,
[WO_PM_PASSFAIL] [smallint] NULL,
[WO_DEPT_HEAD] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_EQ_NOT_LOC] [smallint] NULL,
[WO_EQUIP_RISK] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_EST_START] [datetime] NULL,
[WO_EST_COMP] [datetime] NULL,
[WO_PM_FK] [int] NULL,
[WO_OTHER_COST] [float] NULL,
[WO_EMAILED] [smallint] NULL,
[WO_SPLIT_CHRG] [smallint] NULL,
[WO_REF_NO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_FAC_ID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_EMAIL_ADDR] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_PC_CODE] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_FU_FK] [int] NULL,
[WO_FO_FK] [int] NOT NULL,
[WO_FTR_FK] [int] NOT NULL,
[WO_CL_FK] [int] NULL,
[WO_PC_FK] [int] NULL,
[WO_TECH_REP] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_SR_ACT] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CON_FK] [int] NULL,
[WO_FA_FK] [int] NULL,
[WO_LABOR_ROLL] [float] NULL,
[WO_HOURS_ROLL] [float] NULL,
[WO_PARTS_ROLL] [float] NULL,
[WO_OTHER_ROLL] [float] NULL,
[WO_ROLL_DATE] [datetime] NULL,
[WO_EST_ROLL] [float] NULL,
[WO_ACT_FK] [int] NULL,
[WO_ALT_JOBS] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CONSOLIDATED] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CN_FK] [int] NULL,
[WO_EMAIL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_RQ_FK] [int] NULL,
[WO_RSM_QTY] [float] NULL,
[WO_CREATE_DATE] [datetime] NULL,
[WO_CREATOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_PAID_AMT] [float] NULL,
[WO_SCHED_DATE] [datetime] NULL,
[WO_SCHED_USER] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_ROLL_QTY] [float] NULL,
[WO_ROLL_SAFETY_QTY] [float] NULL,
[WO_NUM_2DP1] [float] NULL,
[WO_NUM_2DP2] [float] NULL,
[WO_NUM_2DP3] [float] NULL,
[WO_NUM_2DP4] [float] NULL,
[WO_NUM_4DP1] [float] NULL,
[WO_NUM_4DP2] [float] NULL,
[WO_NUM_4DP3] [float] NULL,
[WO_NUM_4DP4] [float] NULL,
[WO_NUM_4DP5] [float] NULL,
[WO_NUM_4DP6] [float] NULL,
[WO_NUM_INT_1] [float] NULL,
[WO_NUM_INT_2] [float] NULL,
[WO_BOOLEAN_1] [smallint] NULL,
[WO_BOOLEAN_2] [smallint] NULL,
[WO_BOOLEAN_3] [smallint] NULL,
[WO_BOOLEAN_4] [smallint] NULL,
[WO_BOOLEAN_5] [smallint] NULL,
[WO_BOOLEAN_6] [smallint] NULL,
[WO_CHAR_60_1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_60_2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_30_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_30_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_30_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_30_4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_255_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_255_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_255_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_255_4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_CHAR_255_5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_UD_DATE1] [datetime] NULL,
[WO_UD_DATE2] [datetime] NULL,
[WO_UD_DATE3] [datetime] NULL,
[WO_UD_DATE4] [datetime] NULL,
[WO_UD_DATE5] [datetime] NULL,
[WO_UD_DATE6] [datetime] NULL,
[WO_SOURCE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_COMP_DATE] [datetime] NULL,
[WO_COMP_BY] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_TAX_FK] [int] NULL,
[WO_TAX_RATE] [float] NULL,
[WO_TAX_AMT] [float] NULL,
[WO_TAX_RATE_2] [float] NULL,
[WO_TAX_AMT_2] [float] NULL,
[WO_ITEM_NO_LOC] [smallint] NULL,
[WO_DUE_DATE] [datetime] NULL,
[WO_FD_FK] [int] NULL,
[WO_FB_FK] [int] NULL,
[WO_AUTHORIZED] [smallint] NULL,
[WO_AUTH_DATE] [datetime] NULL,
[WO_LEGACY_AUTH] [smallint] NULL,
[WO_AUTH_REQD] [smallint] NULL,
[WO_REJECT_DATE] [datetime] NULL,
[WO_REJECTOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_REJ_REASON] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_INCL_DETAIL] [smallint] NULL,
[WO_CLIENT_REF] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_LAPSE_CLOSE] [float] NULL,
[WO_LAPSE_COMP] [float] NULL,
[WO_RTS_FK] [int] NULL,
[WO_RTS_SOURCE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_LABOR_RETAIL] [float] NULL,
[WO_PARTS_RETAIL] [float] NULL,
[WO_OTHER_RETAIL] [float] NULL,
[WO_TOTAL_RETAIL] [float] NULL,
[WO_VEN_FK] [int] NULL,
[WO_OVR_ACCT_NO] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WO_FIXED_COST] [smallint] NULL,
[WO_ENCUMB_BAL] [float] NULL,
[WO_ENCUMB_DATE] [datetime] NULL,
[WO_ENCUMB_AMT] [float] NULL,
[WO_EST_ROLL_BAL] [float] NULL,
[WO_FISCAL_START] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
