CREATE TABLE [dbo].[ExcludedGL00100]
(
[ACTINDX] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ExcludedGL00100] ADD CONSTRAINT [PK_ExcludedGL00100] PRIMARY KEY CLUSTERED  ([ACTINDX]) ON [PRIMARY]
GO
