CREATE TABLE [dbo].[f_Buildings]
(
[FB_BLDG_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FB_YTD_LABOR] [float] NULL,
[FB_YTD_PARTS] [float] NULL,
[FB_YTD_TOTAL] [float] NULL,
[FB_PURGE_DATE] [datetime] NULL,
[FB_ORIG_CONTR] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_COMPLETED] [datetime] NULL,
[FB_ORIG_COST] [float] NULL,
[FB_YTD_QTY] [float] NULL,
[FB_PK] [int] NOT NULL,
[FB_LAST_WO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_LAST_DATE] [datetime] NULL,
[FB_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FB_BLDG_DESC] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_REP_COST] [float] NULL,
[FB_CLEAN_OUTS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_SHUTOFFS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_EMERG_INFO] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_ROOF_TYPE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_2ND_CONTR] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_FLOOR_QTY] [float] NULL,
[FB_BLDG_NO] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_LABOR_2] [float] NULL,
[FB_MATER_2] [float] NULL,
[FB_TOTAL_2] [float] NULL,
[FB_LABOR_3] [float] NULL,
[FB_MATER_3] [float] NULL,
[FB_TOTAL_3] [float] NULL,
[FB_LABOR_4] [float] NULL,
[FB_MATER_4] [float] NULL,
[FB_TOTAL_4] [float] NULL,
[FB_LABOR_5] [float] NULL,
[FB_MATER_5] [float] NULL,
[FB_TOTAL_5] [float] NULL,
[FB_LTD_LABOR] [float] NULL,
[FB_LTD_PARTS] [float] NULL,
[FB_LTD_TOTAL] [float] NULL,
[FB_ADDRESS1] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_ADDRESS2] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CITY] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_STATE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_ZIPCODE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_SQ_FOOTAGE] [float] NULL,
[FB_MOD_DATE] [datetime] NULL,
[FB_MOD_USER] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_ARCHIVE_DATE] [datetime] NULL,
[FB_CAPACITY] [float] NULL,
[FB_ROOF_REPL] [datetime] NULL,
[FB_BTU_RATE] [float] NULL,
[FB_ACCT_NO] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_FAC_ID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_ROOF_SLOP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_LABOR_BUD] [float] NULL,
[FB_PARTS_BUD] [float] NULL,
[FB_TOTAL_BUD] [float] NULL,
[FB_CAPIMPRV_YTD] [float] NULL,
[FB_CAPIMPRV_MTD] [float] NULL,
[FB_CAPIMPRV_LTD] [float] NULL,
[FB_ACCUM_DEPREC] [float] NULL,
[FB_DEPRECIAT_YTD] [float] NULL,
[FB_DEPRECIAT_MTD] [float] NULL,
[FB_DEPRECIAT_METH] [float] NULL,
[FB_QTY_YTD_1] [float] NULL,
[FB_QTY_YTD_2] [float] NULL,
[FB_QTY_YTD_3] [float] NULL,
[FB_QTY_YTD_4] [float] NULL,
[FB_DATE_IN_SERVICE] [datetime] NULL,
[FB_DEPRECIAT_LTD] [float] NULL,
[FB_DATE_LST_DEPR] [datetime] NULL,
[FB_SALV_VALUE] [float] NULL,
[FB_RC_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_ROOF_AREA] [float] NULL,
[FB_FD_FK] [int] NOT NULL,
[FB_BAR_CODED] [smallint] NULL,
[FB_SR_FK] [int] NOT NULL,
[FB_UD_DATE1] [datetime] NULL,
[FB_UD_DATE2] [datetime] NULL,
[FB_UD_DATE3] [datetime] NULL,
[FB_UD_DATE4] [datetime] NULL,
[FB_UD_DATE5] [datetime] NULL,
[FB_UD_DATE6] [datetime] NULL,
[FB_NUM_2DP1] [float] NULL,
[FB_NUM_2DP2] [float] NULL,
[FB_NUM_2DP3] [float] NULL,
[FB_NUM_2DP4] [float] NULL,
[FB_BOOLEAN_1] [smallint] NULL,
[FB_BOOLEAN_2] [smallint] NULL,
[FB_BOOLEAN_3] [smallint] NULL,
[FB_BOOLEAN_4] [smallint] NULL,
[FB_BOOLEAN_5] [smallint] NULL,
[FB_BOOLEAN_6] [smallint] NULL,
[FB_CHAR255_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CHAR255_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CHAR255_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CHAR255_4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CHAR255_5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_ACTIVE] [smallint] NULL,
[FB_X_COORD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_Y_COORD] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_YTD_OTHER] [float] NULL,
[FB_OTHER_BUD] [float] NULL,
[FB_OTHER_2] [float] NULL,
[FB_OTHER_3] [float] NULL,
[FB_OTHER_4] [float] NULL,
[FB_OTHER_5] [float] NULL,
[FB_LTD_OTHER] [float] NULL,
[FB_RF_WARR_EXP] [datetime] NULL,
[FB_NUM_INT1] [float] NULL,
[FB_NUM_INT2] [float] NULL,
[FB_CHAR30_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CHAR30_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CHAR30_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CHAR30_4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CHAR60_1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_CHAR60_2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_NUM_4DP1] [float] NULL,
[FB_NUM_4DP2] [float] NULL,
[FB_NUM_4DP3] [float] NULL,
[FB_NUM_4DP4] [float] NULL,
[FB_NUM_4DP5] [float] NULL,
[FB_NUM_4DP6] [float] NULL,
[FB_CREATE_DATE] [datetime] NULL,
[FB_CREATOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_ACQ] [datetime] NULL,
[FB_REMAIN_BASIS] [float] NULL,
[FB_BASIS] [float] NULL,
[FB_DEP_LIFE] [float] NULL,
[FB_MTD_DEP] [float] NULL,
[FB_YTD_DEP] [float] NULL,
[FB_LTD_DEP] [float] NULL,
[FB_LAST_DEP] [datetime] NULL,
[FB_METH] [float] NULL,
[FB_SALV] [float] NULL,
[FB_RATE] [float] NULL,
[FB_AUTO_SW] [smallint] NULL,
[FB_DEP_YEAR] [float] NULL,
[FB_DEP_EXP] [datetime] NULL,
[FB_SW] [smallint] NULL,
[FB_SW_DATE] [datetime] NULL,
[FB_DISP] [datetime] NULL,
[FB_WARR_DATE] [datetime] NULL,
[FB_PARENT_TAG] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_RTS_FK] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
