CREATE TABLE [dbo].[f_Job_Library]
(
[FO_JOB_CODE] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FO_JOB_DESCRIP] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FO_YTD_LABOR] [float] NULL,
[FO_YTD_PARTS] [float] NULL,
[FO_YTD_TOTAL] [float] NULL,
[FO_PURGE_DATE] [datetime] NULL,
[FO_YTD_QTY] [float] NULL,
[FO_YTD_HOURS] [float] NULL,
[FO_PK] [int] NOT NULL,
[FO_PM_TASK_NO] [float] NULL,
[FO_AVERG_TIME] [float] NULL,
[FO_MOD_DATE] [datetime] NULL,
[FO_MOD_USER] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_FIXED_JOB] [smallint] NULL,
[FO_RC_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_FAC_ID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_LAST_DATE] [datetime] NULL,
[FO_LAST_WO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_PM_TASK] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_FJ_FK] [int] NOT NULL,
[FO_TIME_STD] [float] NULL,
[FO_BAR_CODED] [smallint] NULL,
[FO_NOTIFY_REQ] [smallint] NULL,
[FO_NO_TASK] [smallint] NULL,
[FO_HAS_TASK] [smallint] NULL,
[FO_EFFECT_DATE] [datetime] NULL,
[FO_REC_UNIT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_REC_INTERV] [float] NULL,
[FO_CREW] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_UNIT_MEAS] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_EST_PARTS] [float] NULL,
[FO_EST_LABOR] [float] NULL,
[FO_EST_EQUIP] [float] NULL,
[FO_EST_TOTAL] [float] NULL,
[FO_EST_INHOUSE] [float] NULL,
[FO_EST_PROFIT] [float] NULL,
[FO_RS_MEANS] [smallint] NULL,
[FO_ASSEMBLY_NO] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_YTD_OTHER] [float] NULL,
[FO_EST_COST] [float] NULL,
[FO_APPROVE_REQD] [smallint] NULL,
[FO_APPROVE_LEVEL] [float] NULL,
[FO_APPROVE_QTY] [float] NULL,
[FO_PRINT_TASK] [smallint] NULL,
[FO_CREATE_DATE] [datetime] NULL,
[FO_CREATOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FO_ACTIVE] [smallint] NULL,
[FO_MT_TASK] [smallint] NULL,
[FO_USE_CHKLIST] [smallint] NULL,
[FO_INSPECTION] [smallint] NULL,
[FO_CODE_RELATED] [smallint] NULL,
[FO_LABOR_RATE] [float] NULL,
[FO_USE_MODIFIERS] [smallint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
