CREATE TABLE [dbo].[f_Equipment]
(
[FM_TAG_NO] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FM_DESCRIPTION] [varchar] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FM_ACQ_COST] [float] NULL,
[FM_DATE_PURCH] [datetime] NULL,
[FM_WARRANT_EXP] [datetime] NULL,
[FM_SERVCONTR_PH] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PK] [int] NOT NULL,
[FM_YTD_QTY] [float] NULL,
[FM_YTD_LABOR] [float] NULL,
[FM_YTD_PARTS] [float] NULL,
[FM_LAST_WO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_LAST_DATE] [datetime] NULL,
[FM_SERVCONT_YN] [smallint] NULL,
[FM_SERVCONT_EXP] [datetime] NULL,
[FM_YTD_QTY_PM] [float] NULL,
[FM_LST_CERTIFY] [datetime] NULL,
[FM_NEXT_CERTIFY] [datetime] NULL,
[FM_ECRI_CODE] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_YTD_TOTAL] [float] NULL,
[FM_MODEL_NO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_SERIAL_NO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART1_NAME] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART2_NAME] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART3_NAME] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART4_NAME] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART1_SERIAL] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART2_SERIAL] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART3_SERIAL] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART4_SERIAL] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART1_MODEL] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART2_MODEL] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART3_MODEL] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART4_MODEL] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART1_MFGR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART2_MFGR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART3_MFGR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART4_MFGR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_FILTER_INFO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_BELT_1_QTY] [float] NULL,
[FM_SECONDRY_ID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_LIFE_EXPECT] [float] NULL,
[FM_DISP] [datetime] NULL,
[FM_PARTS_VEND] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_SERV_INTERUP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_SAFETY_PREC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_ELECTR_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_ELECTR_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_ELECTR_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_STEAM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_COLD_WATER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_HOT_WATER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_SEWER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_FRESH_AIR] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_GAS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_COMPR_AIR] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_VACUUM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_SUPPLIES] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_BELT_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_BELT_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_BELT_SIZE_1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_BELT_SIZE_2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_FILTER_SIZ_1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_FILTER_SIZ_2] [float] NULL,
[FM_FILTER_OTHER] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR30_1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR30_2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR60_1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR60_2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR255_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR255_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_BOOLEAN1] [smallint] NULL,
[FM_UD_BOOLEAN2] [smallint] NULL,
[FM_UD_BOOLEAN3] [smallint] NULL,
[FM_UD_BOOLEAN4] [smallint] NULL,
[FM_UD_DATE1] [datetime] NULL,
[FM_UD_DATE2] [datetime] NULL,
[FM_UD_NUM_2DP1] [float] NULL,
[FM_UD_NUM_2DP2] [float] NULL,
[FM_UD_INT1] [float] NULL,
[FM_UD_INT2] [float] NULL,
[FM_UD_4DP1] [float] NULL,
[FM_UD_4DP2] [float] NULL,
[FM_UD_4DP3] [float] NULL,
[FM_UD_4DP4] [float] NULL,
[FM_PART_TYPE1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART_TYPE2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART_TYPE3] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PART_TYPE4] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_BELT_QTY2] [float] NULL,
[FM_LUB_EXTRA1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_COMMENTS] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_LTD_LABOR] [float] NULL,
[FM_LTD_PARTS] [float] NULL,
[FM_LTD_TOTAL] [float] NULL,
[FM_MOD_DATE] [datetime] NULL,
[FM_MOD_USER] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_START_HOURS] [float] NULL,
[FM_CURR_METER] [float] NULL,
[FM_RC_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_PWR_USE] [float] NULL,
[FM_RISK_FACT] [float] NULL,
[FM_MAJOR_TAG] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_LAST_PM] [datetime] NULL,
[FM_AMP_DRAW] [float] NULL,
[FM_AMP_RATING] [float] NULL,
[FM_BTU_OUT] [float] NULL,
[FM_BTU_PER_HR] [float] NULL,
[FM_LEASED_YN] [smallint] NULL,
[FM_DELIV_CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_INSPECT_BY] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_INSPECT_DATE] [datetime] NULL,
[FM_LTD_OP_ERS] [float] NULL,
[FM_LTD_PAT_RISK] [float] NULL,
[FM_LST_OP_ER] [datetime] NULL,
[FM_LST_PAT_RISK] [datetime] NULL,
[FM_PURGE_DATE] [datetime] NULL,
[FM_ACTIVE] [smallint] NULL,
[FM_FU_FK] [int] NOT NULL,
[FM_FC_FK] [int] NOT NULL,
[FM_VEN_FK] [int] NULL,
[FM_BLDG_FIXTURE] [smallint] NULL,
[FM_LST_CALIBR] [datetime] NULL,
[FM_FAC_ID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_SY_FK] [int] NULL,
[FM_SO_FK] [int] NULL,
[FM_CN_FK] [int] NULL,
[FM_UD_4DP5] [float] NULL,
[FM_UD_4DP6] [float] NULL,
[FM_PO_NUMBER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_DRWG_NAME] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_TG_FK] [int] NULL,
[FM_MFG_FK] [int] NULL,
[FM_REFRIG_LBS] [float] NULL,
[FM_YTD_OTHER] [float] NULL,
[FM_LTD_OTHER] [float] NULL,
[FM_CF_FK] [int] NULL,
[FM_LAST_INV_DAT] [datetime] NULL,
[FM_DBA_LAST_INV] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_WK_FK] [int] NULL,
[FM_LTD_OP_RISK] [float] NULL,
[FM_LST_OP_RISK] [datetime] NULL,
[FM_ACCT_NO] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_BOOLEAN5] [smallint] NULL,
[FM_UD_BOOLEAN6] [smallint] NULL,
[FM_UD_DATE3] [datetime] NULL,
[FM_UD_DATE4] [datetime] NULL,
[FM_UD_DATE5] [datetime] NULL,
[FM_UD_DATE6] [datetime] NULL,
[FM_UD_NUM_2DP3] [float] NULL,
[FM_UD_NUM_2DP4] [float] NULL,
[FM_UD_CHAR255_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR255_4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR255_5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR30_3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_UD_CHAR30_4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_CONDIT_INVENT] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_CREATE_DATE] [datetime] NULL,
[FM_CREATOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_ACQ] [datetime] NULL,
[FM_REMAIN_BASIS] [float] NULL,
[FM_BASIS] [float] NULL,
[FM_DEP_LIFE] [float] NULL,
[FM_MTD_DEP] [float] NULL,
[FM_YTD_DEP] [float] NULL,
[FM_LTD_DEP] [float] NULL,
[FM_LAST_DEP] [datetime] NULL,
[FM_METH] [float] NULL,
[FM_SALV] [float] NULL,
[FM_RATE] [float] NULL,
[FM_AUTO_SW] [smallint] NULL,
[FM_DEP_YEAR] [float] NULL,
[FM_DEP_EXP] [datetime] NULL,
[FM_SW] [smallint] NULL,
[FM_SW_DATE] [datetime] NULL,
[FM_SUB_LOCATION] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_YTD_HOURS] [float] NULL,
[FM_LTD_QTY] [float] NULL,
[FM_LTD_HOURS] [float] NULL,
[FM_FCS_FK] [int] NULL,
[FM_YTD_TGT_ACI] [float] NULL,
[FM_YTD_ACT_ACI] [float] NULL,
[FM_REPLACE_COST] [float] NULL,
[FM_DAILY_RATE] [float] NULL,
[FM_MONTHLY_RATE] [float] NULL,
[FM_CANCEL_CHARGE] [float] NULL,
[FM_CLEAN_CHARGE] [float] NULL,
[FM_HOURLY_RATE] [float] NULL,
[FM_DISPATCHED] [smallint] NULL,
[FM_RENTABLE] [smallint] NULL,
[FM_METER_RATE] [float] NULL,
[FM_REC_ACCT] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FM_WEEKLY_RATE] [float] NULL
) ON [PRIMARY]
GO
