CREATE TABLE [dbo].[AuditPM00200]
(
[VENDORID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UserName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Operation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVENDNAME] [char] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVNDCHKNM] [char] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVENDSHNM] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVADDCDPR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVADCDPAD] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVADCDSFR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVADCDTRO] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVNDCLSID] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVNDCNTCT] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalADDRESS1] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalADDRESS2] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalADDRESS3] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalCITY] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalSTATE] [char] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalZIPCODE] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalCOUNTRY] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalPHNUMBR1] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalPHNUMBR2] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalPHONE3] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalFAXNUMBR] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalUPSZONE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalSHIPMTHD] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalTAXSCHID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalACNMVNDR] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalTXIDNMBR] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalVENDSTTS] [smallint] NOT NULL,
[OriginalCURNCYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalTXRGNNUM] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalPARVENID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalTRDDISCT] [smallint] NOT NULL,
[OriginalTEN99TYPE] [smallint] NOT NULL,
[OriginalMINORDER] [numeric] (19, 5) NOT NULL,
[OriginalPYMTRMID] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalMINPYTYP] [smallint] NOT NULL,
[OriginalMINPYPCT] [smallint] NOT NULL,
[OriginalMINPYDLR] [numeric] (19, 5) NOT NULL,
[OriginalMXIAFVND] [smallint] NOT NULL,
[OriginalMAXINDLR] [numeric] (19, 5) NOT NULL,
[OriginalCOMMENT1] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalCOMMENT2] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalUSERDEF1] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalUSERDEF2] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalCRLMTDLR] [numeric] (19, 5) NOT NULL,
[OriginalPYMNTPRI] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalKPCALHST] [tinyint] NOT NULL,
[OriginalKGLDSTHS] [tinyint] NOT NULL,
[OriginalKPERHIST] [tinyint] NOT NULL,
[OriginalKPTRXHST] [tinyint] NOT NULL,
[OriginalHOLD] [tinyint] NOT NULL,
[OriginalPTCSHACF] [smallint] NOT NULL,
[OriginalCREDTLMT] [smallint] NOT NULL,
[OriginalWRITEOFF] [smallint] NOT NULL,
[OriginalMXWOFAMT] [numeric] (19, 5) NOT NULL,
[OriginalSBPPSDED] [tinyint] NOT NULL,
[OriginalPPSTAXRT] [smallint] NOT NULL,
[OriginalDXVARNUM] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalCRTCOMDT] [datetime] NOT NULL,
[OriginalCRTEXPDT] [datetime] NOT NULL,
[OriginalRTOBUTKN] [tinyint] NOT NULL,
[OriginalXPDTOBLG] [tinyint] NOT NULL,
[OriginalPRSPAYEE] [tinyint] NOT NULL,
[OriginalPMAPINDX] [int] NOT NULL,
[OriginalPMCSHIDX] [int] NOT NULL,
[OriginalPMDAVIDX] [int] NOT NULL,
[OriginalPMDTKIDX] [int] NOT NULL,
[OriginalPMFINIDX] [int] NOT NULL,
[OriginalPMMSCHIX] [int] NOT NULL,
[OriginalPMFRTIDX] [int] NOT NULL,
[OriginalPMTAXIDX] [int] NOT NULL,
[OriginalPMWRTIDX] [int] NOT NULL,
[OriginalPMPRCHIX] [int] NOT NULL,
[OriginalPMRTNGIX] [int] NOT NULL,
[OriginalPMTDSCIX] [int] NOT NULL,
[OriginalACPURIDX] [int] NOT NULL,
[OriginalPURPVIDX] [int] NOT NULL,
[OriginalNOTEINDX] [numeric] (19, 5) NOT NULL,
[OriginalCHEKBKID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalMODIFDT] [datetime] NOT NULL,
[OriginalCREATDDT] [datetime] NOT NULL,
[OriginalRATETPID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalRevalue_Vendor] [tinyint] NOT NULL,
[OriginalPost_Results_To] [smallint] NOT NULL,
[OriginalFREEONBOARD] [smallint] NOT NULL,
[OriginalGOVCRPID] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalGOVINDID] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalDISGRPER] [smallint] NOT NULL,
[OriginalDUEGRPER] [smallint] NOT NULL,
[OriginalDOCFMTID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OriginalTaxInvRecvd] [tinyint] NOT NULL,
[OriginalUSERLANG] [smallint] NOT NULL,
[OriginalWithholdingType] [smallint] NOT NULL,
[OriginalWithholdingFormType] [smallint] NOT NULL,
[OriginalWithholdingEntityType] [smallint] NOT NULL,
[OriginalTaxFileNumMode] [smallint] NOT NULL,
[OriginalBRTHDATE] [datetime] NOT NULL,
[OriginalLaborPmtType] [smallint] NOT NULL,
[VENDNAME] [char] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VNDCHKNM] [char] (65) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VENDSHNM] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VADDCDPR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VADCDPAD] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VADCDSFR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VADCDTRO] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VNDCLSID] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VNDCNTCT] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADDRESS1] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADDRESS2] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ADDRESS3] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CITY] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STATE] [char] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ZIPCODE] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COUNTRY] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PHNUMBR1] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PHNUMBR2] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PHONE3] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FAXNUMBR] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPSZONE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SHIPMTHD] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TAXSCHID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACNMVNDR] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TXIDNMBR] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VENDSTTS] [smallint] NOT NULL,
[CURNCYID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TXRGNNUM] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PARVENID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TRDDISCT] [smallint] NOT NULL,
[TEN99TYPE] [smallint] NOT NULL,
[MINORDER] [numeric] (19, 5) NOT NULL,
[PYMTRMID] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MINPYTYP] [smallint] NOT NULL,
[MINPYPCT] [smallint] NOT NULL,
[MINPYDLR] [numeric] (19, 5) NOT NULL,
[MXIAFVND] [smallint] NOT NULL,
[MAXINDLR] [numeric] (19, 5) NOT NULL,
[COMMENT1] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMMENT2] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERDEF1] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERDEF2] [char] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRLMTDLR] [numeric] (19, 5) NOT NULL,
[PYMNTPRI] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KPCALHST] [tinyint] NOT NULL,
[KGLDSTHS] [tinyint] NOT NULL,
[KPERHIST] [tinyint] NOT NULL,
[KPTRXHST] [tinyint] NOT NULL,
[HOLD] [tinyint] NOT NULL,
[PTCSHACF] [smallint] NOT NULL,
[CREDTLMT] [smallint] NOT NULL,
[WRITEOFF] [smallint] NOT NULL,
[MXWOFAMT] [numeric] (19, 5) NOT NULL,
[SBPPSDED] [tinyint] NOT NULL,
[PPSTAXRT] [smallint] NOT NULL,
[DXVARNUM] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRTCOMDT] [datetime] NOT NULL,
[CRTEXPDT] [datetime] NOT NULL,
[RTOBUTKN] [tinyint] NOT NULL,
[XPDTOBLG] [tinyint] NOT NULL,
[PRSPAYEE] [tinyint] NOT NULL,
[PMAPINDX] [int] NOT NULL,
[PMCSHIDX] [int] NOT NULL,
[PMDAVIDX] [int] NOT NULL,
[PMDTKIDX] [int] NOT NULL,
[PMFINIDX] [int] NOT NULL,
[PMMSCHIX] [int] NOT NULL,
[PMFRTIDX] [int] NOT NULL,
[PMTAXIDX] [int] NOT NULL,
[PMWRTIDX] [int] NOT NULL,
[PMPRCHIX] [int] NOT NULL,
[PMRTNGIX] [int] NOT NULL,
[PMTDSCIX] [int] NOT NULL,
[ACPURIDX] [int] NOT NULL,
[PURPVIDX] [int] NOT NULL,
[NOTEINDX] [numeric] (19, 5) NOT NULL,
[CHEKBKID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MODIFDT] [datetime] NOT NULL,
[CREATDDT] [datetime] NOT NULL,
[RATETPID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Revalue_Vendor] [tinyint] NOT NULL,
[Post_Results_To] [smallint] NOT NULL,
[FREEONBOARD] [smallint] NOT NULL,
[GOVCRPID] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GOVINDID] [char] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DISGRPER] [smallint] NOT NULL,
[DUEGRPER] [smallint] NOT NULL,
[DOCFMTID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TaxInvRecvd] [tinyint] NOT NULL,
[USERLANG] [smallint] NOT NULL,
[WithholdingType] [smallint] NOT NULL,
[WithholdingFormType] [smallint] NOT NULL,
[WithholdingEntityType] [smallint] NOT NULL,
[TaxFileNumMode] [smallint] NOT NULL,
[BRTHDATE] [datetime] NOT NULL,
[LaborPmtType] [smallint] NOT NULL,
[DEX_ROW_ID] [int] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AuditPM00200] ADD CONSTRAINT [PK_AuditPM00200] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
GRANT INSERT ON  [dbo].[AuditPM00200] TO [drew]
GO
GRANT INSERT ON  [dbo].[AuditPM00200] TO [gloria]
GO
GRANT INSERT ON  [dbo].[AuditPM00200] TO [jean]
GO
GRANT SELECT ON  [dbo].[AuditPM00200] TO [jennifer]
GO
GRANT INSERT ON  [dbo].[AuditPM00200] TO [jennifer]
GO
GRANT DELETE ON  [dbo].[AuditPM00200] TO [jennifer]
GO
GRANT UPDATE ON  [dbo].[AuditPM00200] TO [jennifer]
GO
GRANT INSERT ON  [dbo].[AuditPM00200] TO [lgraves]
GO
GRANT INSERT ON  [dbo].[AuditPM00200] TO [Richard]
GO
GRANT INSERT ON  [dbo].[AuditPM00200] TO [tangleton]
GO
