CREATE TABLE [dbo].[VisionAndScopeDocuments]
(
[ID] [int] NOT NULL,
[AssignmentID] [int] NULL,
[RevisionNumber] [tinyint] NULL,
[CreatedDate] [datetime] NULL,
[Status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Background] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessOpportunity] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ObjectivesAndSuccessCriteria] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VisionStatement] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MajorFeatures] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssumptionsAndDependencies] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScopeOfThisRelease] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScopeOfSubsequentReleases] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LimitationsAndExclusions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StakeholderProfiles] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectPriorities] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperatingEnvironment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeasAnalyst] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DesignCoord] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserRep] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectAdmin] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectSpvsr] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Implementor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportFreq] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubmittedBy] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubmittedDate] [datetime] NULL,
[AuthorizedBy] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizedDate] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
