CREATE TABLE [dbo].[f_PM_Schedules]
(
[PM_START_DATE] [datetime] NULL,
[PM_PK] [int] NOT NULL,
[PM_NEXT_DATE] [datetime] NULL,
[PM_LAST_DATE] [datetime] NULL,
[PM_INTERVAL] [float] NOT NULL,
[PM_UNITS_IDENTI] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PM_FLOAT_STATUS] [smallint] NULL,
[PM_EST_TIME] [float] NULL,
[PM_MOD_DATE] [datetime] NULL,
[PM_MOD_USER] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PM_START_METER] [float] NULL,
[PM_RC_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PM_SEASON_ST] [datetime] NULL,
[PM_SEASON_EN] [datetime] NULL,
[PM_FIXED_DAY] [smallint] NULL,
[PM_LAST_METER] [float] NULL,
[PM_PROJ_DATE] [datetime] NULL,
[PM_AVG_METER] [float] NULL,
[PM_NEXT_METER] [float] NULL,
[PM_MARGIN] [float] NULL,
[PM_RISK_LEVEL] [float] NULL,
[PM_FO_FK] [int] NOT NULL,
[PM_FU_FK] [int] NULL,
[PM_FV_FK] [int] NULL,
[PM_FM_FK] [int] NULL,
[PM_P_FK] [int] NULL,
[PM_TIME] [datetime] NULL,
[PM_FAC_ID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PM_WK_FK] [int] NULL,
[PM_FLOATING] [smallint] NULL,
[PM_CON_FK] [int] NULL,
[PM_CREATE_DATE] [datetime] NULL,
[PM_GRP_FK] [int] NULL,
[PM_ACCT_NO] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PM_EMAIL_LIST] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PM_CR_FK] [int] NULL,
[PM_NS_FK] [int] NULL,
[PM_METER_UNITS] [float] NULL,
[PM_FTR_FK] [int] NULL,
[PM_CE_FK] [int] NULL,
[PM_WO_CHARGE] [smallint] NULL,
[PM_WO_PRIORITY] [float] NULL,
[PM_WH_FK] [int] NULL,
[PM_CN_FK] [int] NULL,
[PM_DAYS_TO_COMP] [float] NULL,
[PM_CRW_FK] [int] NULL,
[PM_CREATOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PM_INCL_DETAIL] [smallint] NULL,
[PM_RTS_FK] [int] NULL,
[PM_RTS_SOURCE] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PM_TYPE_CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
